server:
  port: 8084

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8082/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: add-service
    

  
management:
  security:
    enabled: false

